/*     ___    ____  __    ___   _________
 *    /   |  / _  |/ /   / / | / /__  __/          Source Code Static Analyzer
 *   / /| | / / / / /   / /  |/ /  / /                  AdLint - Advanced Lint
 *  / __  |/ /_/ / /___/ / /|  /  / /
 * /_/  |_|_____/_____/_/_/ |_/  /_/  Copyright (C) 2010-2013, OGIS-RI Co.,Ltd.
 *
 * Project specific initial header file generated by adlintize 1.6.0
 * at 2012-04-23 21:48:10 +0900.
 */

/* Put project specific predefined macros and types here. */
